//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onsoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ord
    {
        public int Id { get; set; }
        public int IdCus { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public string Description { get; set; }
        public string TypePay { get; set; }
        public Nullable<float> Amount { get; set; }
        public string Status { get; set; }
        public string Name { get; set; }
        public string Tel { get; set; }
        public string Address { get; set; }
        public Nullable<int> ProviceId { get; set; }
        public string P_xa { get; set; }
        public string PostCode { get; set; }
        public Nullable<double> PriceVC { get; set; }
        public Nullable<double> Nongthon { get; set; }
        public Nullable<double> PriceNT { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
