//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onsoft.Models
{
    using System;
    
    public partial class sp_Menu_GetByAll_Result
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Tag { get; set; }
        public Nullable<int> IdCategory { get; set; }
        public string Content { get; set; }
        public string Detail { get; set; }
        public string Level { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Keyword { get; set; }
        public string Target { get; set; }
        public string Link { get; set; }
        public Nullable<int> Ord { get; set; }
        public int Position { get; set; }
        public bool Active { get; set; }
        public string Images { get; set; }
    }
}
