//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onsoft.Models
{
    using System;
    
    public partial class sp_Province_Price_GetByAll_Result
    {
        public int Id { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<double> To { get; set; }
        public Nullable<double> From { get; set; }
        public Nullable<double> PriceN { get; set; }
        public Nullable<double> PriceC { get; set; }
        public Nullable<double> PriceO { get; set; }
    }
}
