//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onsoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_News_GroupNews
    {
        public string groupName { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Tag { get; set; }
        public string Title { get; set; }
        public string Keyword { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public System.DateTime SDate { get; set; }
        public string Content { get; set; }
        public string Detail { get; set; }
        public bool Index { get; set; }
        public Nullable<int> View { get; set; }
        public int IdGroup { get; set; }
        public Nullable<int> Ord { get; set; }
        public bool Active { get; set; }
    }
}
