//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onsoft.Models
{
    using System;
    
    public partial class sp_Country_Paging_Result
    {
        public Nullable<long> RowNum { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Logo { get; set; }
        public Nullable<int> Ord { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    }
}
