//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onsoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baocao_Product
    {
        public int IdPro { get; set; }
        public string Name { get; set; }
        public int Number { get; set; }
        public double Price { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public Nullable<int> Soluongmua { get; set; }
    }
}
