//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onsoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size
    {
        public Size()
        {
            this.ExportDetails = new HashSet<ExportDetail>();
            this.ImportDetails = new HashSet<ImportDetail>();
            this.ProSizes = new HashSet<ProSize>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Ord { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> Default { get; set; }
    
        public virtual ICollection<ExportDetail> ExportDetails { get; set; }
        public virtual ICollection<ImportDetail> ImportDetails { get; set; }
        public virtual ICollection<ProSize> ProSizes { get; set; }
    }
}
