//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onsoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Product_DescTotalNumber
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Tag { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public Nullable<int> Weight { get; set; }
        public string ChatLieu { get; set; }
        public Nullable<short> Status { get; set; }
        public string Detail { get; set; }
        public Nullable<int> SpTon { get; set; }
        public int Count { get; set; }
        public int View { get; set; }
        public Nullable<int> Like { get; set; }
        public int IdCategory { get; set; }
        public Nullable<int> IdCategory2 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public bool Index { get; set; }
        public bool Priority { get; set; }
        public string Keyword { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<int> Ord { get; set; }
        public bool Active { get; set; }
        public Nullable<double> PriceRetail { get; set; }
        public Nullable<double> PricePromotion { get; set; }
        public Nullable<int> Num { get; set; }
        public string Noibat { get; set; }
        public string Baohanh { get; set; }
        public string Giamgia { get; set; }
    }
}
