//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onsoft.Models
{
    using System;
    
    public partial class sp_Province_GetById_Result
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Level { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Ord { get; set; }
        public bool Active { get; set; }
        public string Time { get; set; }
        public Nullable<double> Price1 { get; set; }
        public Nullable<double> Price2 { get; set; }
        public string Time1 { get; set; }
        public string Time2 { get; set; }
    }
}
