//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onsoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Permission_GroupProduct
    {
        public string Name { get; set; }
        public Nullable<int> Ord { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<bool> View { get; set; }
        public Nullable<bool> Full { get; set; }
        public int CatPerID { get; set; }
        public Nullable<int> ID { get; set; }
    }
}
