//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onsoft.Models
{
    using System;
    
    public partial class sp_Support_GetById_Result
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public string Nick { get; set; }
        public Nullable<int> Type { get; set; }
        public string Image { get; set; }
        public string Target { get; set; }
        public Nullable<int> Ord { get; set; }
        public string Tel { get; set; }
        public Nullable<int> IdGroupSupport { get; set; }
        public int Position { get; set; }
        public bool Active { get; set; }
    }
}
