//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onsoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_OrderDetail_Product
    {
        public int Id { get; set; }
        public Nullable<int> IdOr { get; set; }
        public int IdPro { get; set; }
        public int IdSize { get; set; }
        public int Number { get; set; }
        public double Price { get; set; }
        public double Total { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public Nullable<int> IdColor { get; set; }
        public string CName { get; set; }
        public string SName { get; set; }
    }
}
